apiVersion: v1
kind: Pod
metadata:
  name: {{ include "performance-insight" . }}
  labels:
    app: {{ include "performance-insight" . }}
    chart: {{ include "performance-insight" . }}
spec:
  hostNetwork: true
      volumes:
        - name: {{ .Values.persistence.name }}
          emptyDir: {}
      containers:
        - name: {{ include "performance-insight-postgres" . }}
          image: "{{ .Values.image.repository1 }}"
          volumeMounts:
          - name: {{ .Values.persistence.name }}
            mountPath: {{ .Values.persistence.mountPath }}
          imagePullPolicy: IfNotPresent
          env:
          - name: "http_proxy"
            value: 'http://194.138.0.25:9400'
          - name: "https_proxy"
            value: 'http://194.138.0.25:9400'
          - name: "no_proxy"
            value: "localhost;127.0.0.1"
          - name: "DBSERVICETYPE"
            value: "postgres"
          - name: "DBSERVICE"
            value: "EdgeDatabase"  
          - name: "VCAP_SERVICES"
            value: "{"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"database-service","port":"5432","username":"postgres","password":"Siemens123"}}]}"
          - name: "EXTENDED_ERRORS"
            value: "true"
          - name: "LOG_DEBUG_INFO"
            value: "true"
          - name: "POSTGRES_DB"
            value: "postgres
          - name: "POSTGRES_USER"
            value: "postgres"
          - name: "POSTGRES_PASSWORD"
            value: "Siemens123"

            
          ports:
          - containerPort: {{ .Values.service.port1 }}
           
